export default {
  games: [
    {
      id: 1,
      title: 'Spider-Man Miles Moreles',
      price: 199.9,
      discountPercentage: 27,
      rating: 5,
      category: 'windows',
      image: 'spider_man_miles_morales.png',
    },
    {
      id: 1,
      title: 'The Last of Us™ Part I',
      price: 249.9,
      discountPercentage: 27,
      rating: 5,
      category: 'windows',
      image: 'the_last_of_us_part_l.png',
    },
    {
      id: 2,
      title: 'GOD OF WAR',
      price: 199.9,
      discountPercentage: 27,
      rating: 5,
      category: 'windows',
      image: 'god_of_war.png',
    },
    {
      id: 3,
      title: 'Marvels Spider-Man Remastered',
      price: 249.9,
      discountPercentage: 27,
      rating: 5,
      category: 'windows',
      image: 'Marvel_Spider-Man_Remastered.png',
    },
    {
      id: 4,
      title: 'Horizon Zero Dawn Complete Edition',
      price: 200,
      discountPercentage: 27,
      rating: 5,
      category: 'windows',
      image: 'Horizon_Zero_Dawn.png',
    },
    {
      id: 5,
      title: 'UNCHARTED Legacy of Thieves Collection',
      price: 199.9,
      discountPercentage: 27,
      rating: 5,
      category: 'windows',
      image: 'UNCHARTED_Legacy_of_Thieves.png',
    },
    {
      id: 6,
      title: 'Days Gone',
      price: 199.9,
      discountPercentage: 27,
      rating: 5,
      category: 'windows',
      image: 'Days_Gone.png',
    },
    {
      id: 7,
      title: 'Diablo IV Ultimate Edition',
      price: 499,
      discountPercentage: 27,
      rating: 5,
      category: 'xbox',
      image: 'Diablo_IV_Ultimate_Edition.png',
    },
    {
      id: 8,
      title: 'Minecraft Legends',
      price: 199,
      discountPercentage: 27,
      rating: 5,
      category: 'xbox',
      image: 'Minecraft_Legends.png',
    },
    {
      id: 9,
      title: 'Halo Infinite',
      price: 249,
      discountPercentage: 27,
      rating: 5,
      category: 'xbox',
      image: 'Halo_Infinite.png',
    },
    {
      id: 10,
      title: 'Ori and the Will of the Wisps',
      price: 99.9,
      discountPercentage: 27,
      rating: 5,
      category: 'xbox',
      image: 'Ori_and_the_Will_of_the_Wisps.png',
    },
    {
      id: 11,
      title: 'Tell Me Why: Capítulo 1-3',
      price: 99.9,
      discountPercentage: 27,
      rating: 5,
      category: 'xbox',
      image: 'Tell_Me_Why.png',
    },
  ],
}
