export default {
  products: [
    {
      id: 0,
      title: 'Mouse Gamer Redragon Cobra',
      description: 'Chroma RGB, 12400DPI, 7 Botões, Preto - M711 V2',
      price: 176.46,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'mouse',
      image: 'Mouse_Gamer_Redragon_Cobra.png',
    },
    {
      id: 1,
      title: 'Headset Gamer Redragon Zeus X',
      description:
        'Chroma Mk.II, RGB, Surround 7.1, USB, Drivers 53MM, Preto/Vermelho - H510-RGB',
      price: 435.28,
      discountPercentage: 15,
      rating: 4.69,
      stock: 20,
      category: 'headset',
      image: 'Headset_Gamer_Redragon_Zeus_X.png',
    },
    {
      id: 2,
      title: 'Mouse Gamer Redragon Cobra',
      description: 'RGB, 7 Botões, 10000DPI, Lunar White - M711W',
      price: 137.64,
      discountPercentage: 7,
      rating: 4.1,
      stock: 3,
      category: 'mouse',
      image: 'Mouse_Gamer_Redragon_Cobra.png',
    },
    {
      id: 3,
      title: 'Teclado Mecânico Gamer HyperX Alloy MKW100',
      description: 'RGB, Switch Red, Full Size, US, Preto - 4P5E1AA#ABA',
      price: 247.05,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'keynboard',
      image: 'Teclado_Mecanico_Gamer_HyperX_Alloy_MKW100.png',
    },
    {
      id: 4,
      title: 'Headset Gamer Havit',
      description:
        'Drivers 53mm, Microfone Plugável, P2, PC, PS4, XBOX ONE, Preto - HV-H2002D',
      price: 210.52,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'headset',
      image: 'Headset_Gamer_Havit.png',
    },
    {
      id: 5,
      title: 'Teclado Mecânico Gamer Redragon Fizz',
      description: 'Rainbow, Switch Brown, Preto - K617-R-B (PT-BROWN)',
      price: 188.22,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'keyboard',
      image: 'Teclado_Mecanico_Gamer_Redragon_Fizz.png',
    },
    {
      id: 6,
      title: 'Mouse Gamer HyperX Pulsefire FPS PRO',
      description: 'RGB, 16000DPI - 4P4F7AA',
      price: 176.46,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'mouse',
      image: 'Mouse_Gamer_HyperX_Pulsefire_FPS_PRO.png',
    },
    {
      id: 7,
      title: 'Microfone Gamer HyperX QuadCast S Podcast',
      description:
        'Antivibração, LED RGB, USB, Compatível com PC, PS4 e Mac - 4P5P7AA',
      price: 941.16,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'microphone',
      image: 'Microfone_Gamer_HyperX_QuadCast_S_Podcast.png',
    },
    {
      id: 8,
      title: 'Mouse Sem Fio Gamer Razer Viper Ultimate',
      description:
        '20000DPI, 8 Botões, Chroma, com Dock, Optical Switch, Preto - RZ01-03050100-R3U1',
      price: 823.52,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'mouse',
      image: 'Mouse_Sem_Fio_Gamer_Razer_Viper_Ultimate.png',
    },
    {
      id: 9,
      title: 'Headset Gamer HyperX Cloud II',
      description:
        'Som Surround 7.1, Drivers 53mm, USB e P3, Preto e Vermelho - 4P5M0AA',
      price: 556.46,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'headset',
      image: 'Headset_Gamer_HyperX_Cloud_II.png',
    },
    {
      id: 10,
      title: 'Headset Sem Fio Gamer HyperX Cloud Stinger Core',
      description: 'Drivers 40mm, PS5 PS4 e PC, Branco e Azul - HHSS1C-KB-WT/G',
      price: 479.99,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'headset',
      image: 'Headset_Sem_Fio_Gamer_HyperX_Cloud_Stinger_Core.png',
    },
    {
      id: 11,
      title: 'Headset Gamer Logitech G332',
      description:
        'Para PC, PlayStation, Xbox e Nintendo Switch, Preto/Vermelho - 981-000755',
      price: 305.87,
      discountPercentage: 27,
      rating: 5,
      stock: 13,
      category: 'headset',
      image: 'Headset_Gamer_Logitech_G332 .png',
    },
  ],
}
